import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";
import Layout from "@/components/layout/Layout/Layout";
import Search from "@/components/Search/Search";

export default function Home() {
  return (
    <>
      <Head>
        <title>DotaImprover</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Search />
      </Layout>
    </>
  );
}
