export const heroes = [
  {
    id: 1,
    localized_name: "Anti-Mage",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 2,
    localized_name: "Axe",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 3,
    localized_name: "Bane",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 4,
    localized_name: "Bloodseeker",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 5,
    localized_name: "Crystal Maiden",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 6,
    localized_name: "Drow Ranger",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 7,
    localized_name: "Earthshaker",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 8,
    localized_name: "Juggernaut",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 9,
    localized_name: "Mirana",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 10,
    localized_name: "Morphling",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 11,
    localized_name: "Shadow Fiend",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 12,
    localized_name: "Phantom Lancer",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 13,
    localized_name: "Puck",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 14,
    localized_name: "Pudge",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 15,
    localized_name: "Razor",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 16,
    localized_name: "Sand King",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 17,
    localized_name: "Storm Spirit",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 18,
    localized_name: "Sven",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 19,
    localized_name: "Tiny",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 20,
    localized_name: "Vengeful Spirit",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 21,
    localized_name: "Windranger",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 22,
    localized_name: "Zeus",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 23,
    localized_name: "Kunkka",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 25,
    localized_name: "Lina",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 26,
    localized_name: "Lion",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 27,
    localized_name: "Shadow Shaman",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 28,
    localized_name: "Slardar",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 29,
    localized_name: "Tidehunter",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 30,
    localized_name: "Witch Doctor",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 31,
    localized_name: "Lich",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 32,
    localized_name: "Riki",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 33,
    localized_name: "Enigma",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 34,
    localized_name: "Tinker",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 35,
    localized_name: "Sniper",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 36,
    localized_name: "Necrophos",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 37,
    localized_name: "Warlock",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 38,
    localized_name: "Beastmaster",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 39,
    localized_name: "Queen of Pain",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 40,
    localized_name: "Venomancer",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 41,
    localized_name: "Faceless Void",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 42,
    localized_name: "Wraith King",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 43,
    localized_name: "Death Prophet",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 44,
    localized_name: "Phantom Assassin",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 45,
    localized_name: "Pugna",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 46,
    localized_name: "Templar Assassin",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 47,
    localized_name: "Viper",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 48,
    localized_name: "Luna",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 49,
    localized_name: "Dragon Knight",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 50,
    localized_name: "Dazzle",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 51,
    localized_name: "Clockwerk",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 52,
    localized_name: "Leshrac",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 53,
    localized_name: "Nature's Prophet",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 54,
    localized_name: "Lifestealer",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 55,
    localized_name: "Dark Seer",
    primary_attr: "int",
    attack_type: "Melee",
},
{
    id: 56,
    localized_name: "Clinkz",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 57,
    localized_name: "Omniknight",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 58,
    localized_name: "Enchantress",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 59,
    localized_name: "Huskar",
    primary_attr: "str",
    attack_type: "Ranged",
},
{
    id: 60,
    localized_name: "Night Stalker",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 61,
    localized_name: "Broodmother",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 62,
    localized_name: "Bounty Hunter",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 63,
    localized_name: "Weaver",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 64,
    localized_name: "Jakiro",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 65,
    localized_name: "Batrider",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 66,
    localized_name: "Chen",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 67,
    localized_name: "Spectre",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 68,
    localized_name: "Ancient Apparition",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 69,
    localized_name: "Doom",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 70,
    localized_name: "Ursa",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 71,
    localized_name: "Spirit Breaker",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 72,
    localized_name: "Gyrocopter",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 73,
    localized_name: "Alchemist",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 74,
    localized_name: "Invoker",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 75,
    localized_name: "Silencer",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 76,
    localized_name: "Outworld Destroyer",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 77,
    localized_name: "Lycan",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 78,
    localized_name: "Brewmaster",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 79,
    localized_name: "Shadow Demon",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 80,
    localized_name: "Lone Druid",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 81,
    localized_name: "Chaos Knight",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 82,
    localized_name: "Meepo",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 83,
    localized_name: "Treant Protector",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 84,
    localized_name: "Ogre Magi",
    primary_attr: "int",
    attack_type: "Melee",
},
{
    id: 85,
    localized_name: "Undying",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 86,
    localized_name: "Rubick",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 87,
    localized_name: "Disruptor",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 88,
    localized_name: "Nyx Assassin",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 89,
    localized_name: "Naga Siren",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 90,
    localized_name: "Keeper of the Light",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 91,
    localized_name: "Io",
    primary_attr: "str",
    attack_type: "Ranged",
},
{
    id: 92,
    localized_name: "Visage",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 93,
    localized_name: "Slark",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 94,
    localized_name: "Medusa",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 95,
    localized_name: "Troll Warlord",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 96,
    localized_name: "Centaur Warrunner",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 97,
    localized_name: "Magnus",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 98,
    localized_name: "Timbersaw",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 99,
    localized_name: "Bristleback",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 100,
    localized_name: "Tusk",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 101,
    localized_name: "Skywrath Mage",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 102,
    localized_name: "Abaddon",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 103,
    localized_name: "Elder Titan",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 104,
    localized_name: "Legion Commander",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 105,
    localized_name: "Techies",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 106,
    localized_name: "Ember Spirit",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 107,
    localized_name: "Earth Spirit",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 108,
    localized_name: "Underlord",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 109,
    localized_name: "Terrorblade",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 110,
    localized_name: "Phoenix",
    primary_attr: "str",
    attack_type: "Ranged",
},
{
    id: 111,
    localized_name: "Oracle",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 112,
    localized_name: "Winter Wyvern",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 113,
    localized_name: "Arc Warden",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 114,
    localized_name: "Monkey King",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 119,
    localized_name: "Dark Willow",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 120,
    localized_name: "Pangolier",
    primary_attr: "agi",
    attack_type: "Melee",
},
{
    id: 121,
    localized_name: "Grimstroke",
    primary_attr: "int",
    attack_type: "Ranged",
},
{
    id: 123,
    localized_name: "Hoodwink",
    primary_attr: "agi",
    attack_type: "Ranged",
},
{
    id: 126,
    localized_name: "Void Spirit",
    primary_attr: "int",
    attack_type: "Melee",
},
{
    id: 128,
    localized_name: "Snapfire",
    primary_attr: "str",
    attack_type: "Ranged",
},
{
    id: 129,
    localized_name: "Mars",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 135,
    localized_name: "Dawnbreaker",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 136,
    localized_name: "Marci",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 137,
    localized_name: "Primal Beast",
    primary_attr: "str",
    attack_type: "Melee",
},
{
    id: 138,
    localized_name: "Muerta",
    primary_attr: "int",
    attack_type: "Ranged",
}
]